### ISSUE TITLE
Deployment target version

### ISSUE THREAD

**Issue by Elamuruga** [pedrommcarrasco/Hover#12]
@pedrommcarrasco Could you please help me downgrade the deployment version to support IOS 10.0. It will be very useful to me. Thanks in advance

**Comment by pedrommcarrasco** [comment]
What's blocking you from doing it @Elamuruga? Is there any specific API that we use not compatible with iOS 10.0?
Keep in mind that I have no personal reason for downgrading the deployment version since supporting older versions can be troublesome as we move forward.

This said, you can always, create a fork of this repo and apply your changes 👍

**Comment by Elamuruga** [comment]
> What's blocking you from doing it @Elamuruga? Is there any specific API that we use not compatible with iOS 10.0?
> Keep in mind that I have no personal reason for downgrading the deployment version since supporting older versions can be troublesome as we move forward.
> 
> This said, you can always create a fork of this repo and apply your changes 👍

Thanks for your immediate response. I will do it once again thank you a lot
